### ISSUE TITLE
Boat "air" brush

### ISSUE THREAD

**Issue by rilifon** [rilifon/liquidum#138]
A brush that marks a cell as "doesn't have a boat".
We don't necessarily need to use it on internal grid logic, but it can be quite useful for players

**Comment by yancouto** [comment]
Would also help solver a little.

I had to do a less elegant solution on 9b04ea9638d6f4e2b28d52bdbe30eeb35d0a601c

**Comment by yancouto** [comment]
Tricky: Boat air might also be in a place where there might be water in the future, different from normal air

**Comment by yancouto** [comment]
Model stuff done on 3c6d9cdf6eb1ac878709034c4a73898a9b80b53b
