### ISSUE TITLE
Track down solver bug

### ISSUE THREAD

**Issue by yancouto** [rilifon/liquidum#77]
Something to do with the together rule on columns I think. Sometimes when generating interesting 7x7 levels the solver crashes. It seems we put more water than we should on a column or row.

Not too big, but annoying sometimes.

**Comment by rilifon** [comment]
Might be related, this level the solver says its unsolvable
![image](https://github.com/rilifon/liquidum/assets/3944304/58b42bac-efc5-45d8-bfd8-10ac6eebc093)
